targets:
  $default:
    builders:
      json_serializable:
        options:
          create_to_json: true
          explicit_to_json: true
global_options:
  dart_mappable_builder:
    options:
      renameMethods:
        fromJson: fromJsonString
        toJson: toJsonString
        fromMap: fromJson
        toMap: toJson